version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  payment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres